### ISSUE TITLE
ntdll.h

### ISSUE THREAD

**Issue by SystemTDX1** [yo-aiv1/RevConnection#1]
I downloaded the repo and installed everything i needed, added to enviorment vars and i get this error

Error: `PARSING... DONE
COMPILING...In file included from src\../include/main.h:8,
                 from src\main.c:1:
src\../include/ntdll.h:11251:5: error: unknown type name 'PCFG_CALL_TARGET_INFO'
     PCFG_CALL_TARGET_INFO ptOffsets;
     ^~~~~~~~~~~~~~~~~~~~~
In file included from src\../include/main.h:8,
                 from src\loaders.c:1:
src\../include/ntdll.h:11251:5: error: unknown type name 'PCFG_CALL_TARGET_INFO'
     PCFG_CALL_TARGET_INFO ptOffsets;
     ^~~~~~~~~~~~~~~~~~~~~
In file included from src\../include/main.h:8,
                 from src\utils.c:1:
src\../include/ntdll.h:11251:5: error: unknown type name 'PCFG_CALL_TARGET_INFO'
     PCFG_CALL_TARGET_INFO ptOffsets;
     ^~~~~~~~~~~~~~~~~~~~~
x86_64-w64-mingw32-gcc: error: main.o: No such file or directory
x86_64-w64-mingw32-gcc: error: loaders.o: No such file or directory
x86_64-w64-mingw32-gcc: error: utils.o: No such file or directory
DONE
CLEANING... DONE

THE EXECUTABLE IS LOCATED AT: bin\main.exe`

**Comment by youlha1** [comment]
what OS do you use? also what is the version of x86_64-w64-mingw32-gcc?
you can get it by running ```x86_64-w64-mingw32-gcc --version```

**Comment by SystemTDX1** [comment]
windows 10 22H2 and x86_64-w64-mingw32-gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Comment by youlha1** [comment]
its because of the compiler, try getting the latest version from winlibs

**Comment by SystemTDX1** [comment]
> winlibs



> its because of the compiler, try getting the latest version from winlibs

Okay perfect ill try now

**Comment by SystemTDX1** [comment]
perfect worked great and made the exe called main.exe how does the shell work. how do i listen to the "victim" computer after they execute it

**Comment by SystemTDX1** [comment]
is it possible to change the code to accept more than ipv4 so it can take ddns aswell

**Comment by youlha1** [comment]
you can use any socket listener, like netcat, unfortunately no you can change it.
