### ISSUE TITLE
Undefined reference to 'GetPEB()'

### ISSUE THREAD

**Issue by j0seRey** [yo-aiv1/RevConnection#2]
PARSING... DONE
COMPILING/usr/bin/x86_64-w64-mingw32-ld: src/loaders.o:loaders.c:(.text$_Z13GetDllAddressm+0xa): undefined reference to `GetPEB()'
collect2: error: ld returned 1 exit status
make: *** [makefile:39: link] Error 1

**Comment by youlha1** [comment]
fixed, reclone the repo also make sure nasm is installed

**Comment by youlha1** [comment]
dont forget to star the repo if you find it helpful
