### ISSUE TITLE
GCC for Windows

### ISSUE THREAD

**Issue by sec13b** [yo-aiv1/RevConnection#4]
Windows
Download and install the GNU Compiler Collection (GCC) for Windows from [winlibs](https://winlibs.com/#download-release). Make sure to add the installation directory to your system path environment variable during installation.

https://github.com/brechtsanders/winlibs_mingw/releases/download/14.1.0posix-18.1.8-12.0.0-ucrt-r3/winlibs-x86_64-posix-seh-gcc-14.1.0-llvm-18.1.8-mingw-w64ucrt-12.0.0-r3.7z

can make a simple tutorial , how to install ?

thank you

**Comment by youlha1** [comment]
it is easy to install it on windows as any other program, you can look in youtube for such video there are a lot.
