### ISSUE TITLE
two Issues

### ISSUE THREAD

**Issue by ussamasaeed** [yo-aiv1/RevConnection#5]
First 
![Ist](https://github.com/user-attachments/assets/f91eec4f-5f14-4170-89a7-b1a7e5630d28)
 and
second is 
![2nd](https://github.com/user-attachments/assets/3eb20650-cca4-4179-b28c-ac444000145a)

**Comment by yo-aiv1** [comment]
what version of make you have?
run make --version

**Comment by youlha1** [comment]
i fixed it, pull the new version of the repo
